version: "3"

services:
  transactions_db:
    container_name: ${DB_HOST}
    image: postgres:16rc1-alpine3.18
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 120
    restart: always
    volumes:
      - transactions_db_volume:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  backend:
    depends_on:
      transactions_db:
        condition: service_healthy
    build: .
    container_name: backend
    restart: always
    ports:
      - 3002:3002
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}

volumes:
  transactions_db_volume:
    external: false
